replicaCount: 1

image:
  repository: harbor-01a.corp.local/avinetworks/ako
  pullPolicy: IfNotPresent

AKOSettings:
  logLevel: "INFO"
  fullSyncFrequency: "1800"
  apiServerPort: 8080
  deleteConfig: "false"
  disableStaticRouteSync: "false"
  clusterName: "mycluster01"
  cniPlugin: "calico"

NetworkSettings:
  nodeNetworkList: []
  subnetIP: "10.184.64.0"
  subnetPrefix: "20"
  networkName: "VM Network"

### This section outlines all the knobs  used to control Layer 7 loadbalancing settings in AKO.
L7Settings:
  defaultIngController: "true"
  l7ShardingScheme: "hostname"
  serviceType: NodePort
  shardVSSize: "LARGE"
  passthroughShardSize: "SMALL"

### This section outlines all the knobs  used to control Layer 4 loadbalancing settings in AKO.
L4Settings:
  defaultDomain: "avi.cloud.com"

### This section outlines settings on the Avi controller that affects AKO's functionality.
ControllerSettings:
  serviceEngineGroupName: "Default-Group"
  controllerVersion: "20.1.1"
  cloudName: "Default-Cloud"
  controllerIP: "xxxxxx"

nodePortSelector: # Only applicable if serviceType is NodePort
  key: "avi-lb"
  value: "yes"

resources:
  limits:
    cpu: 250m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 75Mi

podSecurityContext: {}
  # fsGroup: 2000


avicredentials:
  username: "xxxx"
  password: "xxxxxx"


service:
  type: ClusterIP
  port: 80


persistentVolumeClaim: ""
mountPath: "/log"
logFile: "avi.log"
